import Head from 'next/head'
import MainPage from '../components/MainPage';
import Navbar from '../components/Navbar'
import ProjectBar from '../components/ProjectBar';
import TaskBody from '../components/TaskBody';
export default function Home({children}) {
  return (
    <>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <MainPage></MainPage>
      </main>
    </>
  );
}
