import Head from 'next/head'
import Navbar from '../components/Navbar'
import ProjectBar from '../components/ProjectBar';
import TaskBody from '../components/TaskBody';
import "react-datepicker/dist/react-datepicker.css";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="grid grid-cols-8 pt-5 bg-[#ecf0f3] h-screen">
          <div className="col-span-2 flex">
            <Navbar></Navbar>
            <ProjectBar></ProjectBar>
          </div>
          <div className="col-span-5">
            <TaskBody></TaskBody>
          </div>
        </section>
      </main>
    </>
  );
}
